[pytest]
filterwarnings =
    ignore::PendingDeprecationWarning
    ignore::DeprecationWarning
addopts = -v --tb=short
python_functions = test_*
python_classes = Test*
python_files = test_*.py
testpaths = tests

