steps:
- name: 'gcr.io/$PROJECT_ID/generic-transformation:latest'
  env:
  - 'GCP_PROJECT_ID=$_PROJECT_ID'
  - 'RUN_ID=$BUILD_ID'
  args: ['run', '--target', 'prod']

- name: 'gcr.io/$PROJECT_ID/generic-transformation:latest'
  env:
  - 'GCP_PROJECT_ID=$_PROJECT_ID'
  - 'RUN_ID=$BUILD_ID'
  args: ['test', '--target', 'prod']

options:
  logging: CLOUD_LOGGING_ONLY
