mapped_product_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID', 'dummy-project') }}"
      dataset: fdp_generic
      threads: 4
    int:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: fdp_generic
      threads: 4
