"""
LOA Configuration Module.

System-specific configuration for the LOA (Loan Origination Application) pipeline.
"""

from .settings import (
    SYSTEM_ID,
    REQUIRED_ENTITIES,
    ODP_DATASET,
    FDP_DATASET,
    LANDING_BUCKET_TEMPLATE,
    ARCHIVE_BUCKET_TEMPLATE,
    ERROR_BUCKET_TEMPLATE,
    ODP_APPLICATIONS_TABLE,
    ODP_APPLICATIONS_ERRORS_TABLE,
    FDP_EVENT_TRANSACTION_EXCESS_TABLE,
    FDP_PORTFOLIO_ACCOUNT_EXCESS_TABLE,
    JOB_CONTROL_DATASET,
    JOB_CONTROL_TABLE,
    APPLICATIONS_FILE_PATTERN,
    OK_FILE_SUFFIX,
)
from .constants import (
    APPLICATIONS_HEADERS,
    ALLOWED_APPLICATION_STATUSES,
    ALLOWED_APPLICATION_TYPES,
    ALLOWED_ACCOUNT_STATUSES,
    ALLOWED_ACCOUNT_TYPES,
    ALLOWED_EVENT_TYPES,
    ALLOWED_TRANSACTION_TYPES,
    ALLOWED_EXCESS_STATUSES,
    LOAN_AMOUNT_MIN,
    LOAN_AMOUNT_MAX,
    INTEREST_RATE_MIN,
    INTEREST_RATE_MAX,
    LOAN_TERM_MIN,
    LOAN_TERM_MAX,
)

__all__ = [
    # Settings
    'SYSTEM_ID',
    'REQUIRED_ENTITIES',
    'ODP_DATASET',
    'FDP_DATASET',
    'LANDING_BUCKET_TEMPLATE',
    'ARCHIVE_BUCKET_TEMPLATE',
    'ERROR_BUCKET_TEMPLATE',
    'ODP_APPLICATIONS_TABLE',
    'ODP_APPLICATIONS_ERRORS_TABLE',
    'FDP_EVENT_TRANSACTION_EXCESS_TABLE',
    'FDP_PORTFOLIO_ACCOUNT_EXCESS_TABLE',
    'JOB_CONTROL_DATASET',
    'JOB_CONTROL_TABLE',
    'APPLICATIONS_FILE_PATTERN',
    'OK_FILE_SUFFIX',
    # Constants
    'APPLICATIONS_HEADERS',
    'ALLOWED_APPLICATION_STATUSES',
    'ALLOWED_APPLICATION_TYPES',
    'ALLOWED_ACCOUNT_STATUSES',
    'ALLOWED_ACCOUNT_TYPES',
    'ALLOWED_EVENT_TYPES',
    'ALLOWED_TRANSACTION_TYPES',
    'ALLOWED_EXCESS_STATUSES',
    'LOAN_AMOUNT_MIN',
    'LOAN_AMOUNT_MAX',
    'INTEREST_RATE_MIN',
    'INTEREST_RATE_MAX',
    'LOAN_TERM_MIN',
    'LOAN_TERM_MAX',
]

